#!/bin/sh --

DIR=$(dirname $0)
. $DIR/include.sh

speed=$( $SUDO lshw -C processor | 
       grep -E "size: [[:digit:]]+MHz" | 
       sed -e "s/\s*size: //" | 
       sed -e "s/MHz//" )

if [[ "$speed" == "empty" ]]; then
  echo "None"
else
  echo $speed | awk '{print $1}'
fi
