#!/bin/sh

if dmidecode | grep IPMI; then
	  modprobe ipmi_si
	  modprobe ipmi_devintf
fi

export FACTERLIB=/probe/facter 
/usr/bin/facter > /probe.output

URL=$(cat /proc/cmdline | grep -o 'to=[^ ]*' | sed -e 's/to=//')

python /probe/probe-put.py ${URL} /probe.output

